In [ ]:
#Exp_no:7

In [ ]:
#Name:Tanisha S Gour
#Roll no:71
#Sec:B
#Subject:ET1
#Date:04/9/2025

In [ ]:
#Aim: Simple linear Regression

# Simple Linear Regression

In [4]:
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\Asus'

In [7]:
os.chdir("C:\\Users\\Asus\\OneDrive\\Desktop")

In [8]:
df=pd.read_csv("Salary_Data.csv")

In [9]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [10]:
df.shape

(30, 2)

In [11]:
df.size

60

In [12]:
df.tail

<bound method NDFrame.tail of     YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0>

In [13]:
df.ndim

2

In [14]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [15]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [17]:
df.isna()

    YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False

In [18]:
df.isna().any()

YearsExperience    False
Salary             False
dtype: bool

In [19]:
df.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

# Independent and Dependent Variables

In [20]:
x=df.drop('Salary',axis=1)

In [21]:
x.head()

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [22]:
y=df.Salary

In [23]:
y.head()

0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
Name: Salary, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.30)

In [26]:
print(x_train.shape)

(21, 1)

In [27]:
x_test.shape

(9, 1)

# Model Fitting

In [28]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [29]:
m= LR.coef_

In [30]:
print("Coefficient :",m)

Coefficient : [9360.26128619]

In [31]:
c= LR.intercept_

In [32]:
print("Intercept :",c)

Intercept : 26777.39134119764

# Evaluation Metrics

In [33]:
from sklearn import metrics

In [35]:
Accuracy = LR.score(x_test, y_test)
Accuracy

0.9740993407213511