In [ ]:
#Exp_no:3

In [ ]:
#Aim: Creating the Dataframe

In [ ]:
#Name:Tanisha S Gour
#Roll no:71
#Sec:B
#Subject:ET1
#Date:07/8/2025

# Creating Series

In [1]:
 import pandas as pd

In [3]:
Name=["Komal","Nandini","Avantika","Bhumi","Riddhi"]
Name

['Komal', 'Nandini', 'Avantika', 'Bhumi', 'Riddhi']

In [4]:
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1       Komal
2     Nandini
3    Avantika
4       Bhumi
5      Riddhi
dtype: object

# Creating Data Frame

In [6]:
 import pandas as pd

In [7]:
df=pd.DataFrame([[10,15,17,18],[12,14,15,17],[11,12,13,15],[12,13,14,16],[12,13,15,12]],
columns= ["CD","CAO","DBMS","DSS"])

In [8]:
df

   CD  CAO  DBMS  DSS
0  10   15    17   18
1  12   14    15   17
2  11   12    13   15
3  12   13    14   16
4  12   13    15   12

In [9]:
 df.shape

(5, 4)

In [10]:
df.size

20

In [11]:
df.ndim

2

# Adding Record (row) to the data frame

In [12]:
df2=pd.DataFrame([[5,8,9,7]],
columns= ["CD","CAO","DBMS","DSS"])

In [14]:
df3 = pd.concat([df, df2], ignore_index=True)

In [15]:
df3

   CD  CAO  DBMS  DSS
0  10   15    17   18
1  12   14    15   17
2  11   12    13   15
3  12   13    14   16
4  12   13    15   12
5   5    8     9    7

# Adding Attribute (coloumn) in a data frame

In [18]:
df3["DM"]=[12,15,12,7,12,7]

In [19]:
df3

   CD  CAO  DBMS  DSS  DM
0  10   15    17   18  12
1  12   14    15   17  15
2  11   12    13   15  12
3  12   13    14   16   7
4  12   13    15   12  12
5   5    8     9    7   7

# Deleting Record from Data Frame

In [20]:
df4=df3.drop(1)

In [21]:
df4

   CD  CAO  DBMS  DSS  DM
0  10   15    17   18  12
2  11   12    13   15  12
3  12   13    14   16   7
4  12   13    15   12  12
5   5    8     9    7   7

# Deleting Attribute (Coloumns) from df3 dataframe

In [23]:
df5=df3.drop(columns=["DM"])

In [24]:
df5

   CD  CAO  DBMS  DSS
0  10   15    17   18
1  12   14    15   17
2  11   12    13   15
3  12   13    14   16
4  12   13    15   12
5   5    8     9    7

In [25]:
print("Mean of DSS:", df5["DSS"].mean())

Mean of DSS: 14.166666666666666

In [28]:
print("Median of DSS:", df5["DSS"].median())

Median of DSS: 15.5

In [29]:
print("Mode of DSS:", df5["DSS"].mode())

Mode of DSS: 0     7
1    12
2    15
3    16
4    17
5    18
Name: DSS, dtype: int64